# Яременко Вікторія Практична робота №1. Варіант 31(1)

1. Створіть одновимірний масив (вектор) з останніми 10-ма натуральними числами та виведіть його значення.  

In [3]:

nat_numbers = list(range(1, 11))
print(nat_numbers)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.

In [5]:

matrix = [[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]

for row in matrix:
    print(row)


[1, 1, 1, 1]
[1, 1, 1, 1]
[1, 1, 1, 1]
[1, 1, 1, 1]


3. Створіть масив розміром 4x4, заповніть його випадковими цілими числами в діапазоні від 1 до 100 та виведіть його значення.

In [6]:
import random

matrix = [[random.randint(1, 100) for _ in range(4)] for _ in range(4)]

for row in matrix:
    print(row)


[62, 58, 66, 54]
[13, 38, 70, 82]
[82, 35, 31, 19]
[47, 23, 86, 34]


4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [7]:
import random

matrix = [[random.uniform(0, 1) for _ in range(3)] for _ in range(3)]

for row in matrix:
    print(row)


[0.31535699469375855, 0.790767956609774, 0.47361714456672166]
[0.2747382174748981, 0.9839198365127712, 0.18112614248998438]
[0.749307734917304, 0.7120234456332561, 0.2797667218591786]


5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [8]:
import random

array1 = [random.randint(1, 20) for _ in range(6)]
array2 = [random.randint(1, 20) for _ in range(6)]

print("Масив 1:", array1)
print("Масив 2:", array2)

# Виконуємо додавання
addition_result = [x + y for x, y in zip(array1, array2)]
print("Додавання:", addition_result)

# Виконуємо віднімання
subtraction_result = [x - y for x, y in zip(array1, array2)]
print("Віднімання:", subtraction_result)

# Виконуємо множення
multiplication_result = [x * y for x, y in zip(array1, array2)]
print("Множення:", multiplication_result)


Масив 1: [12, 10, 19, 17, 14, 15]
Масив 2: [4, 14, 7, 15, 3, 9]
Додавання: [16, 24, 26, 32, 17, 24]
Віднімання: [8, -4, 12, 2, 11, 6]
Множення: [48, 140, 133, 255, 42, 135]


6. Створіть два вектори розміром 5, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.

In [9]:

vector1 = [7, 5, 7, 2, 1]
vector2 = [1, 4, 2, 9, 8]

scalar_product = sum(x * y for x, y in zip(vector1, vector2))

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Скалярний добуток:", scalar_product)


Вектор 1: [7, 5, 7, 2, 1]
Вектор 2: [1, 4, 2, 9, 8]
Скалярний добуток: 67


7. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та перемножте їх між собою.

In [10]:
import numpy as np

matrix1 = np.random.randint(1, 21, size=(3, 2))
matrix2 = np.random.randint(1, 21, size=(2, 4))

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

# Перемножуємо матриці
result_matrix = np.dot(matrix1, matrix2)

print("\nРезультат множення матриць:")
print(result_matrix)


Матриця 1:
[[17 12]
 [ 1 20]
 [16 11]]

Матриця 2:
[[11 11 16  5]
 [19  9 18 18]]

Результат множення матриць:
[[415 295 488 301]
 [391 191 376 365]
 [385 275 454 278]]


8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.

In [11]:
import numpy as np

matrix = np.random.randint(1, 8, size=(2, 2))

print("Початкова матриця:")
print(matrix)

# Знаходимо обернену матрицю
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nМатриця не має оберненої матриці, оскільки її визначник дорівнює 0.")


Початкова матриця:
[[5 1]
 [2 4]]

Обернена матриця:
[[ 0.22222222 -0.05555556]
 [-0.11111111  0.27777778]]


9. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [12]:
import numpy as np

matrix = np.random.rand(3, 3)

print("Початкова матриця:")
print(matrix)

# Транспонуємо матрицю
transposed_matrix = np.transpose(matrix)

print("\nТранспонована матриця:")
print(transposed_matrix)


Початкова матриця:
[[0.33049276 0.41201743 0.54408825]
 [0.6717581  0.21002957 0.3717928 ]
 [0.14490489 0.71599873 0.98148532]]

Транспонована матриця:
[[0.33049276 0.6717581  0.14490489]
 [0.41201743 0.21002957 0.71599873]
 [0.54408825 0.3717928  0.98148532]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму елементів отриманого вектору.

In [13]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)

# Знаходимо суму елементів вектора
vector_sum = np.sum(vector)

print("\nСума елементів вектора:", vector_sum)


Матриця:
[[5 8 1 2]
 [5 5 8 6]
 [7 3 7 4]]

Вектор:
[6 8 2 1]

Сума елементів вектора: 17


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [14]:
import numpy as np

matrix = np.random.randint(1, 11, size=(2, 3))
vector = np.random.randint(1, 11, size=3)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)

# Знаходимо добуток матриці на вектор
result = np.dot(matrix, vector)

print("\nДобуток матриці на вектор:")
print(result)


Матриця:
[[ 4  6 10]
 [ 8  7  7]]

Вектор:
[ 5  2 10]

Добуток матриці на вектор:
[132 124]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму.

In [15]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

# Знаходимо суму матриць
result_matrix = matrix1 + matrix2

print("\nСума матриць:")
print(result_matrix)


Матриця 1:
[[8 4]
 [3 5]]

Матриця 2:
[[8 8]
 [2 6]]

Сума матриць:
[[16 12]
 [ 5 11]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть їх добуток.

In [16]:
import numpy as np

matrix1 = np.random.rand(2, 2)
matrix2 = np.random.rand(2, 2)

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

# Знаходимо добуток матриць
result_matrix = np.dot(matrix1, matrix2)

print("\nДобуток матриць:")
print(result_matrix)


Матриця 1:
[[0.13202672 0.78797307]
 [0.17540375 0.19291545]]

Матриця 2:
[[0.50612173 0.29474445]
 [0.67329174 0.50802272]]

Добуток матриць:
[[0.59735735 0.43922236]
 [0.21866403 0.14970472]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть суму елементів матриці.

In [17]:
import numpy as np

matrix = np.random.rand(5, 5)

print("Матриця:")
print(matrix)

# Знаходимо суму елементів матриці
matrix_sum = np.sum(matrix)

print("\nСума елементів матриці:", matrix_sum)


Матриця:
[[0.53108487 0.78071494 0.61623533 0.78147549 0.74483797]
 [0.25053383 0.86861805 0.73717413 0.38969412 0.06613581]
 [0.22630637 0.85232    0.77925307 0.30313589 0.4741116 ]
 [0.06170307 0.34337397 0.05517108 0.85805243 0.28849261]
 [0.79068626 0.80115727 0.34385508 0.6770526  0.02484827]]

Сума елементів матриці: 12.646024088076597


15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [18]:
import numpy as np

matrix = np.random.uniform(-1, 1, size=(3, 3))

print("Матриця:")
print(matrix)

# Знаходимо вектор-стовпчик, що містить суму елементів кожного рядка матриці
row_sums = np.sum(matrix, axis=1)

# Перетворюємо вектор-рядок на вектор-стовпчик
column_vector = row_sums.reshape(-1, 1)

print("\nВектор-стовпчик сум рядків матриці:")
print(column_vector)


Матриця:
[[ 0.70287408  0.31046249  0.6936223 ]
 [ 0.69826983  0.22357757 -0.22166041]
 [-0.87746577 -0.82531017 -0.73505119]]

Вектор-стовпчик сум рядків матриці:
[[ 1.70695888]
 [ 0.70018699]
 [-2.43782713]]


 Висновок: У цій практичній роботі я вивчила, як працювати з матрицями та векторами в мові програмування Python, використовуючи бібліотеку NumPy. Я також розглянула такі операції, як створення матриць та векторів з випадковими числами, заповнення їх певними значеннями, обчислення суми елементів, знаходження добутку матриць та векторів, а також транспонування матриць.